version: 2

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage


azstorage:
  type: block
  account-name: ${ACCOUNT_NAME}
  account-key: ${ACCOUNT_KEY}
  container: ${CONTAINER_NAME}

file_cache:
  path: /tmp/blobfuse2_cache
  timeout-sec: 120
  max-size-mb: 4096