version: 2

logging:
  type: syslog
  level: log_warning

components:
  - libfuse
  - azure_storage
  - file_cache
  - attr_cache

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

azure_storage:
  account-name: ${ACCOUNT_NAME}
  account-key: ${ACCOUNT_KEY}
  container-name: ${CONTAINER_NAME}

file_cache:
  path: /tmp/blobfuse2_cache
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 120
